apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test
spec:
  selector:
    app: test  # Matches the pod label
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80  # Port on the pod
  type: ClusterIP    # Use NodePort or LoadBalancer if needed


  